COMMAND CFS CFE_ES_TLM_POOL_STATS BIG_ENDIAN "This command allows the user to obtain a snapshot of the statistics maintained for a specified memory pool."
  APPEND_ID_PARAMETER CCSDS_STREAMID 16 UINT MIN_UINT16 MAX_UINT16 CMD_ERROR "CCSDS Packet Identification"
  APPEND_PARAMETER CCSDS_SEQUENCE 16 UINT MIN_UINT16 MAX_UINT16 0xC000 "CCSDS Packet Sequence Control"
  APPEND_PARAMETER CCSDS_LENGTH 16 UINT MIN_UINT16 MAX_UINT16 0 "CCSDS Packet Data Length"
  APPEND_PARAMETER CCSDS_FC 8 UINT MIN_UINT8 MAX_UINT8 0 "CCSDS Command Function Code"
  APPEND_PARAMETER CCSDS_CHECKSUM 8 UINT MIN_UINT8 MAX_UINT8 0 "CCSDS Command Checksum"
  APPEND_ARRAY_PARAMETER APPLICATION 8 UINT 160 "RESERVED - should be all zeroes"
  APPEND_PARAMETER POOLHANDLE 32 UINT MIN_UINT32 MAX_UINT32 0 "Handle of Pool whose statistics are to be telemetered."

