COMMAND CFS CFE_ES_PERF_SETFILTERMASK BIG_ENDIAN "This command sets the Performance Analyzer's Filter Masks."
  APPEND_ID_PARAMETER CCSDS_STREAMID 16 UINT MIN_UINT16 MAX_UINT16 0x1806 "CCSDS Packet Identification" BIG_ENDIAN
  APPEND_PARAMETER CCSDS_SEQUENCE 16 UINT MIN_UINT16 MAX_UINT16 0xC000 "CCSDS Packet Sequence Control" BIG_ENDIAN
  APPEND_PARAMETER CCSDS_LENGTH 16 UINT MIN_UINT16 MAX_UINT16 1 "CCSDS Packet Data Length" BIG_ENDIAN
  APPEND_PARAMETER CCSDS_CHECKSUM 8 UINT MIN_UINT8 MAX_UINT8 0 "CCSDS Command Checksum"
  APPEND_PARAMETER CCSDS_FC 8 UINT MIN_UINT8 MAX_UINT8 16 "CCSDS Command Function Code"
  APPEND_PARAMETER FILTERMASKNUM 32 UINT MIN_UINT32 MAX_UINT32 0 "Index into array of Filter Masks."
  APPEND_PARAMETER FILTERMASK 32 UINT MIN_UINT32 MAX_UINT32 0 "New Mask for specified entry in array of Filter Masks."

