COMMAND CFS SC_ENABLE_RTSGRP BIG_ENDIAN "The enable state for an RTS may be ENABLED or DISABLED. This command sets the enable state for the specified group of RTS to ENABLED."
  APPEND_ID_PARAMETER CCSDS_STREAMID 16 UINT MIN_UINT16 MAX_UINT16 0x18 "CCSDS Packet Identification"
  APPEND_PARAMETER CCSDS_SEQUENCE 16 UINT MIN_UINT16 MAX_UINT16 0xC000 "CCSDS Packet Sequence Control"
  APPEND_PARAMETER CCSDS_LENGTH 16 UINT MIN_UINT16 MAX_UINT16 0 "CCSDS Packet Data Length"
  APPEND_PARAMETER CCSDS_FC 8 UINT MIN_UINT8 MAX_UINT8 16 "CCSDS Command Function Code"
  APPEND_PARAMETER CCSDS_CHECKSUM 8 UINT MIN_UINT8 MAX_UINT8 0 "CCSDS Command Checksum"
  APPEND_PARAMETER FIRSTRTSID 16 UINT MIN_UINT16 MAX_UINT16 0 "ID of the first RTS to act on, 1 through SC_NUMBER_OF_RTS."
  APPEND_PARAMETER LASTRTSID 16 UINT MIN_UINT16 MAX_UINT16 0 "ID of the last RTS to act on, 1 through SC_NUMBER_OF_RTS."

