COMMAND CFS SCH_DISABLE BIG_ENDIAN "This command disables a single activity in the Schedule Definition Table."
  APPEND_ID_PARAMETER CCSDS_STREAMID 16 UINT MIN_UINT16 MAX_UINT16 0x1895 "CCSDS Packet Identification"
  APPEND_PARAMETER CCSDS_SEQUENCE 16 UINT MIN_UINT16 MAX_UINT16 0xC000 "CCSDS Packet Sequence Control"
  APPEND_PARAMETER CCSDS_LENGTH 16 UINT MIN_UINT16 MAX_UINT16 0 "CCSDS Packet Data Length"
  APPEND_PARAMETER CCSDS_FC 8 UINT MIN_UINT8 MAX_UINT8 3 "CCSDS Command Function Code"
  APPEND_PARAMETER CCSDS_CHECKSUM 8 UINT MIN_UINT8 MAX_UINT8 0 "CCSDS Command Checksum"
  APPEND_PARAMETER SLOTNUMBER 16 UINT MIN_UINT16 MAX_UINT16 0 "Slot Number of Activity whose state is to change."
  APPEND_PARAMETER ENTRYNUMBER 16 UINT MIN_UINT16 MAX_UINT16 0 "Entry Number of Activity whose state is to change."

